name: Deploy
on:
    push:
        branches: [production]

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-angular.yml@master
        with:
            host: codestar.ir
            base-href: /
            project-name: codestar
